Update to Rider 251
JetBrains/aspire-plugin pull request #286
Opened 2024-11-05 19:20 UTC by Fantoom

Fix LaunchSettingsJsonService instance

2024-11-07 17:17 UTC, ForNeVeR requested changes

2024-11-07 17:17 UTC, ForNeVeR commented on src/main/kotlin/com/jetbrains/rider/aspire/run/AspireHostConfigurationType.kt
> +        withContext(Dispatchers.Default) {
This is not really required. Let me eclose `LaunchSettingsJsonService.getInstance(project).loadLaunchSettings` into `Dispatchers.IO`; should be better this way.

2024-11-07 17:17 UTC, ForNeVeR commented on build.gradle.kts
> +    instrumentCode = false //TODO: remove before push
Let's leave this as-is for now. We'll decide what to do with this internally.

2024-11-07 17:19 UTC, ForNeVeR approved these changes
Thanks!

2024-11-07 17:20 UTC, merged

2024-11-11 07:15 UTC, rafaelldi commented
@Fantoom @ForNeVeR Hello, folks. Thank you for the fix! But I have to revert it, because for now the plugin must target the 243 release in the main branch. When we are ready, I will reapply your fix.